### ISSUE TITLE
Error when parsing ellipsis in unquoted string

### ISSUE THREAD

**Issue by Tate-CC** [saphyr-rs/saphyr#22]
Hi again 👋

I'm encountering another parsing issue(using saphyr 0.0.3) when trying to parse a document with an unquoted string containing an ellipsis surrounded by whitespace, e.g.
```
comment: hello ... world
```
fails with `unexpected end of plain scalar at byte 15 line 1 column 16` but succeeds in yaml-rust2.

The parsing does succeed if the string is quoted and or if there isn't any space on either side of the ellipsis, e.g.
```
comment: hello ...world
other_comment: 'hello ... world'
```
parses successfully.

**Comment by Ethiraric** [comment]
Thanks for your report! This should be fixed on `master`.

**Comment by Tate-CC** [comment]
Thanks for jumping on this @Ethiraric 🙏 Would it be possible to get another release to crates with this fix?
